{% set name = "static-frame" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d3560c217ddce07086578387874901b255381df891c5e370de7df904d14d69a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - numpy >=1.23.5
    - arraykit ==1.1.0
    - typing-extensions >=4.12.0

test:
  imports:
    - static_frame

about:
  home: https://github.com/static-frame/static-frame
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Immutable and statically-typeable DataFrames with runtime type and data validation

  description: |
    Among the many Python DataFrame libraries, StaticFrame is an alternative that prioritizes correctness, maintainability, and reducing opportunities for error. Key features include:

    * 🛡️ Immutable Data: Provides memory efficiency, excellent performance, and prohibits side effects.
    * 🗜️ Static Typing: Use Python type-hints to statically type index, columns, and columnar types.
    * 🚦 Runtime Validation: Use type hints and specialized validators for runtime type and data checks.
    * 🧭 Consistent Interface: An easy-to-learn, hierarchical, and intuitive API that avoids the many inconsistencies of Pandas.
    * 🧬 Comprehensive ``dtype`` Support: Full compatibility with all NumPy dtypes and datetime64 units.
    * 🔗 Broad Interoperability: Translate between Pandas, Arrow, Parquet, CSV, TSV, JSON, MessagePack, Excel XLSX, SQLite, HDF5, and NumPy; output to xarray, VisiData, HTML, RST, Markdown, LaTeX, and Jupyter notebooks.
    * 🚀 Optimized Serialization & Memory Mapping: Fast disk I/O with custom NPZ and NPY encodings.
    * 💼 Multi-Table Containers: The ``Bus`` and ``Yarn`` provide interfaces to collections of tables with lazy data loading, well-suited for large datasets.
    * ⏳ Deferred Processing: The ``Batch`` provides a common interface for deferred processing of groups, windows, or any iterator.
    * 🪶 Lean Dependencies: Core functionality relies only on NumPy and team-maintained C-extensions.
    * 📚 Comprehensive Documentation: All API endpoints documented with thousands of easily runnable examples.

  doc_url: https://static-frame.readthedocs.io
  dev_url: https://github.com/static-frame/static-frame

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
