{% set name = "static-frame" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b345b82ea9c4e8605e27268e4f668eb456d2ad2d9c0d948dd65cc74b8886cca7


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.14.2

test:
  imports:
    - static_frame

about:
  home: https://github.com/InvestmentSystems/static-frame
  license: MIT
  license_family: MIT
  summary: 'Immutable structures for one- and two-dimensional calculations with labelled axis'

  description: |
    The StaticFrame library consists of the Series and Frame, immutable data structures
    for one- and two-dimensional calculations with self-aligning, labelled axes.
    StaticFrame offers an alternative to Pandas. While many interfaces for data
    extraction and manipulation are similar to Pandas, StaticFrame deviates from Pandas
    in many ways: all data is immutable, and all indices must be unique; all vector
    processing uses NumPy, and the full range of NumPy data types is preserved;
    the implementation is concise and lightweight; consistent naming and interfaces
    are used throughout; and flexible approaches to iteration and function application,
    with built-in options for parallelization, are provided.
  doc_url: https://static-frame.readthedocs.io
  dev_url: https://github.com/InvestmentSystems/static-frame

extra:
  recipe-maintainers:
    - flexatone
    - brandtbucher
