travis:
  secure:
    BINSTAR_TOKEN: QhPjDKNAdNj6nIopMPHnGXT2YpkRWXMafNS+A/qNORVs6mWUPOjlLUXANa9clUHiAYGnp/o/KJuZbkjQuh2wLHhncwcdHy8Uicn6CbfOJgJ+vN3WPeQjQrSPW8mNJqIlEbFFC+ZGN3EWJji+OJ2S5UQlpvJMVE7EJXPQNw4nPk2aZOzjELh8pgzF9dmmyNr9gZiop6VzFWiciXZpbgG+QKq4kEvwneixvt0UscM7jD1hvBrVLrRadh/+YtvvvVodFN/jjwz0JyXLfn3py5TVxZ1PeuUyRMEx13wHbVYTYCLFfCSdZULnLjPA6Dd4yed/eSOKHywiZTYg1wpjUQesagnLGHGeRxzDUyMyQdru+DcIB0XvdAyn40Qf/8G0mf1YXXtFVJ3m2JlASnHrteFqkmNuR2ulunF3VcSB3o3Qn13uGDSa8e6QqAPGrZ5/UoSF1IA8GheRsGR/JK40WQllPMZLP6660+GPc+1EFv4wvoTwzm5qjMU9gOtBOCg3fl2CDd3hCSBNZs3ccVRRKfdRlKgD0ikfhXlhEG//9SttljEuN7a+VXc0ApVDjCiejX5gpwFWcYX/GK7Lk+KBoV7n4gJV8EmZhfifVulr/9jFOfs15WwWZBEh5bqJLkbJa9mD26nmXZ4w/avliCixL033HtUk/mwl93fe4L6YbTXFQzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
